# Generated by Django 4.0.3 on 2022-03-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishrecord_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='images/'),
        ),
    ]
