# Generated by Django 4.0.3 on 2022-03-27 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishrecord_api', '0002_record_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ('timestamp',)},
        ),
    ]
